export const ROUTERS = {
  LEGAL_DISCLAIMER: "/legal-and-compliance",
  PRIVACY_POLICY: "/privacy-policy",
  TERMS_OF_SERVICE: "/terms-of-service",
  DEVICE_DROP_CAMPAIGN_POLICY: "/device-drop-campaign",
  FAQs: "/faqs",
  HOME: "/",
  ABOUT_US: "/about-us",
  PRODUCTS_AND_SERVICES: "/products-and-services",
  TECHNOLOGY_AND_INNOVATION: "/technology-and-innovation",
  KYC: "/ekyc",
  APPLY_KYC: "/ekyc/apply",
  KYC_CONFIRMATION: "/ekyc/confirmation",
  KYC_TRACKING: "/ekyc/tracking",
};
