on:
  push:
    branches: ["main", "develop"]
  workflow_dispatch:

env:
  NODE_VERSION: "16.x" # set this to the node version to use
  PROJECT_NAME: "nott-landingpage"
  CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: npm install, build, and test
        run: |
          npm install -g yarn
          npm install -g wrangler
          yarn install
          CI=false && yarn build
          echo "CLOUDFLARE_ACCOUNT_ID=${{ env.CLOUDFLARE_ACCOUNT_ID }} $CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_API_TOKEN=${{ env.CLOUDFLARE_API_TOKEN }} $CLOUDFLARE_API_TOKEN"
          wrangler pages publish out --project-name=${{ env.PROJECT_NAME }} --branch=${GITHUB_REF##*/} --commit-hash=${{ env.GITHUB_SHA }}